version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          post-steps: 
            - store_artifacts:
                when: always
                path: cypress/reports/html