name: API tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v6
      - uses: actions/upload-artifact@v3
        with:
          name: Mochawesome-Report
          path: cypress/reports/html
